### ISSUE TITLE
Feature: Add data access control

### ISSUE THREAD

**Issue by ytittes** [SwissOpenEM/Ingestor#129]
Add a way to control file access based off of Scicat group membership.
Key features:

- [ ] control access to files/folders via scicat group membership
- [ ] read a e.g. ".group_access" file for list of allowed groups (in a given directory)
- [ ] have syntax to deny (all)
- [ ] for nested folders access is inherited
- [ ] default: allow all

**Comment by consolethinks** [comment]
This is just a first proposal for a file like this:

`openem-access.yaml`, at an example path of `/home/ingestor/datasetCollection`, with `600` access rights on the file itself and the **file owner** is the same as the one that runs the ingestor service
```yaml
# not sure if this is needed, but maybe it's a good idea to have an integrity check of the access control file
# by stating the path within it
Path: "/home/ingestor/datasetCollection"
# AccessGroups could be changed to something else, depending on what makes the most sense semantically
AccessGroups:
  - group1
  - group2
  - group3
  - "..."
```

In lower level folders, new access groups can't be added, only further restrictions can be created by the presence of the file itself and omitting some of the access groups.

Eg. a valid lower level `openem-access.yaml` file at `home/ingestor/datasetCollection/group1` looks like this:
```yaml
Path: "/home/ingestor/datasetCollection/group1"
AccessGroups:
  - group1
```
And an invalid one:
```yaml
Path: "/home/ingestor/datasetCollection/group2"
AccessGroups:
  - group2
  - group4
```
Additionally, should I derive the "ownerGroups" attribute of the dataset metadata based on these files? Should the requester be able to narrow down, or define new owners if they're authorized themself to access these datasets?

**Comment by sbliven** [comment]
## Filename

The file should be hidden and should make it clear it's a scicat ingestor file. I suggest `.scicat_acl` or `.ingestor_acl`

## Permissions

> 600 access rights on the file itself and the file owner is the same as the one that runs the ingestor service

That seems like a good practice, but I don't think we need to enforce it. I would be inclined to accept any file that the ingestor can read. In some cases you might even want users to be able to set their own acls (implying it would be owned by the data owner but readable by the ingestor)

## Ownership

> Additionally, should I derive the "ownerGroups" attribute of the dataset metadata based on these files? Should the requester be able to narrow down, or define new owners if they're authorized themself to access these datasets?

No, I think the user should be able to ingest as a group that's not on this list. For example, the acl might give access to a single group for all instrument users, but then users want to ingest data under particular projects.

## Contents

I don't see a need to include the Path. This is always the parent directory of the file, right? Adding the path just makes it harder to copy acls around.

Otherwise the contents look reasonable. If it only includes a single AccessGroups list we could get away with a simpler format, but making it YAML future-proofs it if we want to add other properties.

### Allow/deny all

We agreed that if this file is missing then it is treated as an 'allow all', but we should have a way of specifying this explicitly. How about a `default: allow|deny` field, with `deny` as the default. So an empty (but existing) file would deny everyone and be equivalent to:

```yaml
default: deny
accessGroups: []
```

Reversing this allows black-listing users (I can't think of any use-case for this, but people find it useful in .htaccess files).

```yaml
default: allow
accessGroups:
- problem_users
```
