### ISSUE TITLE
Task persistency

### ISSUE THREAD

**Issue by consolethinks** [SwissOpenEM/Ingestor#25]
Implement a way to store tasks in a persistent way so that when the service or GUI app crashes it can load back up the list of tasks in order to continue them.

**Comment by consolethinks** [comment]
This is still an open question in the way it should be implemented @sbliven

**Comment by sbliven** [comment]
I think we have now decided to persist data transfer tasks as scicat jobs. This was discussed in [2025-01-24 Scicat storageLocation
](https://psich.atlassian.net/wiki/x/D4CoDg). The idea is that the ingestor would create the following job:

```yaml
# POST /api/v4/jobs
type: transfer
statusCode: jobStarted
statusMessage: Data queued for transfer by globus
jobParams:
  storageLocation: CSCS # must match dataset storageLocation
  landingZone: globus     # must be valid for the storageLocation
  datasetsList:
    - pid: XXX
      files: []
```
(The `storageLocation` and `landingZone` are provisional.)

The task could then issue progress updates:
```yaml
# PATCH /api/v4/jobs/JOB_ID
statusCode: inProgress
statusMessage: Data transfer 55% complete
```
```yaml
# PATCH /api/v4/jobs/JOB_ID
statusCode: finishedSuccessful
statusMessage: Data transfer 100% complete
```

All spellings are just suggestions.
