### ISSUE TITLE
Support file list in POST /dataset

### ISSUE THREAD

**Issue by sbliven** [SwissOpenEM/Ingestor#40]
Support passing a list of files for ingestion. Files should be relative to `sourceFolder`.

This is required for the SwissFel usecase. They would like to replace calling `datasetIngestor metadata.json fileListing.txt` with a REST call to the PSI Ingestor service.

`POST /dataset` currently takes body `{metadata: string}`.

I suggest this change to something like
```yaml
{
  properties: {
    metadata: {$ref: 'https://scicat.development.psi.ch/explorer-json#/components/schemas/CreateRawDatasetObsoleteDto'},
    fileListing: {
      type: "array",
      items: {type:"string"}
    }
  },
  required: ["metadata"]
}
```
(or whatever this path stabilizes to)
